name:                spdx-document
version:             0.1.0.0
github:              "maxhbr/spdx-document"
license:             BSD3
author:              "Maximillian Huber"
maintainer:          "gh@maxhbr.de"
copyright:           "Maximilian Huber"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/maxhbr/spdx-document#readme>

dependencies:
- base >= 4.7 && < 5
# data types
- text
- bytestring
- Cabal # for SDPX expressions
- spdx # for SDPX.Extra
- network-uri # URI
- fgl # Martin Erwig's Functional Graph Library
# containers
- vector
- hashable
- containers
- unordered-containers
# parsing
- aeson
- aeson-pretty
- yaml
# file handling
- filepath
- directory


library:
  source-dirs: src

executables:
  spdx-document-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spdx-document

tests:
  spdx-document-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spdx-document
    - hspec
    - QuickCheck
    - file-embed
    - temporary
