resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/6.yaml

packages:
- .

extra-deps:
- diagrams-graphviz-1.4.1.1@sha256:e71afa8f89904c2a6a2cb490dba7108c6425779c2174b90bd90dbaf507a9d3dc,1388
- git: https://github.com/phadej/spdx
  commit: ef1807e08299150e4b42dfb33e87e2982be8d49c

